### ISSUE TITLE
Add like\dislike counters in Telegram

### ISSUE THREAD

**Issue by i1bgv** [xxblx/webquotes#4]
Now it looks like:
```
#105: 
Взялся за гуж, не говори, что не дюж
like / dislike
```
I suggest the following:
```
#105: 
Взялся за гуж, не говори, что не дюж
5 like / 3 dislike
```
or
```
#105: 
Взялся за гуж, не говори, что не дюж
like (5)/ dislike (3)
```
The general idea is to show the amount of likes and dislikes in bot's posts

**Comment by xxblx** [comment]
I guess it's possible to implement a solution based on callbacks. I am not familiar with Telegram Bot API in depth, but text updating should not be a big deal. I'll look into it later.

**Comment by i1bgv** [comment]
I meant adding it just for /random or /get commands, it's not supposed to be updated after it's posted 🍻

**Comment by xxblx** [comment]
https://github.com/xxblx/webquotes/commit/d9bb4201633c4189611b345617e130a2364effef
